import './globals.css';

export const metadata = {
  viewport: 'width=device-width, initial-scale=1',
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
